os: linux
dist: bionic
language: php

services:
  - memcached
  - redis
  - mongodb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
- bash ./install_couchdb.sh
script: true