os: linux
dist: bionic
language: php
addons:
  apt:
    sources:
      - https://apache.bintray.com/couchdb-deb
    packages:
      - couchdb

services:
  - memcached
  - redis
  - mongodb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
# Memcached is not yet available for PHP8 (hasn't been updated since 2019): https://pecl.php.net/package/memcached
# Memcache however seems to be compatible with PHP 7 and 8: https://pecl.php.net/package/memcache
#
  - |
    echo "\$TRAVIS_PHP_VERSION set to: $TRAVIS_PHP_VERSION";
    pecl channel-update pecl.php.net;
    yes | pecl install -f mongodb-stable;
    yes | pecl install -f apcu-stable || true;
    yes | pecl install -f memcache;
    ./bin/ci/scripts/setup_couchbase.sh;
    yes | pecl install -f couchbase-stable;
  - |
    if [[ $TRAVIS_PHP_VERSION == "8."* || $TRAVIS_PHP_VERSION == "nightly" ]]; then
        phpenv config-add bin/ci/php8_phpfastcache.ini;
    else
        phpenv config-add bin/ci/php7_phpfastcache.ini;
    fi
  - phpenv config-add bin/ci/php_common.ini;
  - phpenv config-rm xdebug.ini

script: true
