os: linux
dist: bionic
language: php

before_install:
  - sudo apt-get -y install libxml2-dev

addons:
  apt:
    sources:
      - https://apache.bintray.com/couchdb-deb
    packages:
      - couchdb

services:
  - memcached
  - redis
  - mongodb
  - couchdb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

script: true