os: linux
dist: bionic
language: php

before_install:
  - sudo apt update
  - sudo apt-get install -y software-properties-common
  - sudo apt install -y wget
  - wget https://couchdb.apache.org/repo/bintray-pubkey.asc
  - sudo apt-key add bintray-pubkey.asc
  - echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee –a /etc/apt/sources.list
  - sudo apt update
  - sudo apt-get install couchdb

services:
  - memcached
  - redis
  - mongodb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

script: true