os: linux
dist: bionic
language: php

services:
  - memcached
  - redis
  - mongodb

php:
  - 7.3
  - 7.4
  - 8.0
  #- nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
# Memcached is not yet available for PHP8 (hasn't been updated since 2019): https://pecl.php.net/package/memcached
# Memcache however seems to be compatible with PHP 7 and 8: https://pecl.php.net/package/memcache
#
  - sudo apt update && sudo apt install -y curl apt-transport-https gnupg
 
  - curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
 
  - source /etc/os-release

  - echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null

  - sudo apt update 
  - sudo apt install -y couchdb
script:
  - curl http://127.0.0.1:5984/