os: linux
dist: bionic
language: php

services:
  - memcached
  - redis
  - mongodb
  - couchdb

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

script: true